### ISSUE TITLE
Always on option?

### ISSUE THREAD

**Issue by BayuDC** [traperwaze/heroku_capulus#2]

**Comment by 9d4** [comment]
What do you mean with Always on option? Could you please tell us more about it 🙏

**Comment by BayuDC** [comment]
so i want this thing to work 24/7 instead of 13 hours only (start at 6 am and end at 19 pm)

**Comment by 9d4** [comment]
It's by design. To reduce the dyno hours usage, we can set the startAt and stopAt based on the timezone where user lived.

**Comment by BayuDC** [comment]
i want this thing to have 2 options:
- always-on
- in-between

**Comment by 9d4** [comment]
It is such a good thing. But should we make it?

**Comment by BayuDC** [comment]
just make it!

**Comment by 9d4** [comment]
Well like yeah

**Comment by 9d4** [comment]
We got it [v1.2.0](https://github.com/9d4/heroku_capulus/releases/tag/v1.2.0)
